version: "1"

nodes:
  - id: apply-transforms
    name: Apply Lingui useLingui Macro Transformations
    type: automatic
    steps:
      - name: "Scan TypeScript/JavaScript files and migrate t(i18n) pattern to useLingui macro"
        js-ast-grep:
          js_file: scripts/codemod.ts
          language: "typescript"
