version: "1"

nodes:
  - id: apply-transforms
    name: Apply Lingui Macro Import Transformations
    type: automatic
    steps:
      - name: "Scan TypeScript/JavaScript files and migrate @lingui/macro imports"
        js-ast-grep:
          js_file: scripts/codemod.ts
          language: "typescript"
